import {
  ArrowLeftRight,
  Ban,
  Clock,
  Headphones,
  MoreHorizontal,
  Package,
  ShoppingCart,
  Target,
} from "lucide-react-native";

export const SERVICES = [
  {
    id: "dnd",
    label: "DND",
    icon: Ban,
    image: require("@/assets/images/icons/dnd.png"),
    url: "https://dnd.completeselular.com",
    color: "#ef4444",
  },
  {
    id: "sumo",
    label: "Sumo",
    icon: ShoppingCart,
    image: require("@/assets/images/icons/sumo.png"),
    url: "https://sumo.completeselular.com/",
    color: "#f59e0b",
  },
  {
    id: "helpdesk",
    label: "Helpdesk",
    icon: Headphones,
    image: require("@/assets/images/icons/helpdesk.png"),
    url: "https://helpdesk.completeselular.com",
    color: "#10b981",
  },
  {
    id: "lead",
    label: "Lead",
    icon: Target,
    image: require("@/assets/images/icons/lead.png"),
    url: "http://lead.completeselular.com/",
    color: "#8b5cf6",
  },
  {
    id: "shelf",
    label: "Shelf",
    icon: Package,
    image: require("@/assets/images/icons/shelf.png"),
    url: "https://shelf.completeselular.com/",
    color: "#3b82f6",
  },
  {
    id: "attendance",
    label: "Attendance",
    icon: Clock,
    image: require("@/assets/images/icons/attendance.png"),
    url: "https://attendance.completeselular.com/",
    color: "#06b6d4",
  },
  {
    id: "form-transfer",
    label: "Form Transfer",
    icon: ArrowLeftRight,
    image: require("@/assets/images/icons/transfer.png"),
    url: "/form-transfer",
    color: "#ec4899",
  },
  {
    id: "lainnya",
    label: "Lainnya",
    icon: MoreHorizontal,
    image: require("@/assets/images/icons/more.png"),
    url: "",
    color: "#6b7280",
  },
];
